# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rest', '0017_sucursal_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='photo',
        ),
        migrations.AddField(
            model_name='sucursal',
            name='image',
            field=models.ImageField(default=1, upload_to='albums/imagnes'),
            preserve_default=False,
        ),
    ]
