# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rest', '0019_remove_sucursal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='image',
            field=models.ImageField(default=1, upload_to='albums/images/'),
            preserve_default=False,
        ),
    ]
