# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rest', '0024_sucursal_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='imagen',
        ),
        migrations.AddField(
            model_name='sucursal',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
