# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rest', '0026_auto_20160821_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='image',
            field=models.FileField(upload_to='/imagenes/'),
        ),
    ]
