# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 04:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rest', '0029_auto_20160824_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='sigla',
        ),
    ]
