# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rest', '0030_remove_sucursal_sigla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='latitud',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='longitud',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
