# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rest', '0031_auto_20160824_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='iva_producto',
        ),
        migrations.AddField(
            model_name='productos',
            name='image',
            field=models.FileField(default=1, upload_to='productos/'),
            preserve_default=False,
        ),
    ]
