# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rest', '0032_auto_20160824_0438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='image',
            new_name='image_producto',
        ),
    ]
